version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/api/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
