sudo: false

language: python
python:
  - 3.6
  - 3.5
env:
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=lint
cache:
  directories:
    - ~/.cache/pip
    - node_modules

install:
  - pip install tox
  - nvm install node
  - nvm use node
  - npm install
  - npm install gulp-cli
script:
  - node_modules/.bin/gulp fonts styles scripts images
  - tox -e $TOX_ENV
