serve:
  admin:
    cors:
      debug: true
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://localhost:4444
  consent: http://localhost:3001/oauth/consent
  login: http://localhost:3001/oauth/login
  logout: http://localhost:3001/account/logout/
  error: http://localhost:3001/error

dsn: postgres://hangar:hangar@db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
