server:
  port: 8080
spring:
  datasource:
    url: "${POSTGRES_URL}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver

auth:
  kratos:
    admin-url: "https://hangarauth_kratos:4434"
