serve:
  admin:
    cors:
      debug: true
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: https://hangar-auth.benndorf.dev
  consent: https://hangar-auth.benndorf.dev/oauth/consent
  login: https://hangar-auth.benndorf.dev/oauth/login
  logout: https://hangar-auth.benndorf.dev/account/logout/
  error: https://hangar-auth.benndorf.dev/error

dsn: "see env"

secrets:
  system:
    - "see env"

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: "see env"
