serve:
  admin:
    cors:
      debug: true
    tls:
      enabled: false
  cookies:
    same_site_mode: Lax
  public:
    tls:
      allow_termination_from:
        - 10.0.0.0/16
        - 127.0.0.0/16

urls:
  self:
    public: https://hangar-auth.benndorf.dev/hydra
    issuer: https://hangar-auth.benndorf.dev
  consent: https://hangar-auth.benndorf.dev/oauth/consent
  login: https://hangar-auth.benndorf.dev/oauth/login
  logout: https://hangar-auth.benndorf.dev/account/logout/
  error: https://hangar-auth.benndorf.dev/error

dsn: "see env"

secrets:
  system:
    - "see env"

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: "see env"
