version: '3.7'

services:
  frontend:
    image: "ghcr.io/papermc/hangarauth_frontend"
    build:
      context: ../..
      dockerfile: docker/deployment/frontend/Dockerfile
    environment:
      # keep these in sync with build.yml action!
      host: "0.0.0.0"
      publicHost: "https://hangar-auth.benndorf.dev"
      SECRETS_COOKIE: "supersecuresupersecure"
      cookieHttps: "true"
      kratosPublic: "https://hangar-auth.benndorf.dev/kratos"
      kratos: "http://kratos:4433"
      hydraAdmin: "http://hydra:4445"
      hydraPublic: "https://hangar-oauth.benndorf.dev"
      hangarHost: "https://hangar.benndorf.dev"
      DEBUG: "nuxt:*"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.hangar-auth.loadbalancer.server.port=3001"
      - "traefik.http.routers.hangar-auth-kratos.rule=Host(`hangar-auth.benndorf.dev`) && PathPrefix(`/kratos`)"
      - "traefik.http.routers.hangar-auth-kratos.entrypoints=web-secure"
      - "traefik.http.routers.hangar-auth.kratos.service=hangar-kauth"
      - "traefik.http.routers.hangar-auth.rule=Host(`hangar-auth.benndorf.dev`)"
      - "traefik.http.routers.hangar-auth.entrypoints=web-secure"
      - "traefik.http.routers.hangar-auth.tls=true"
      - "traefik.http.routers.hangar-auth.tls.options=default"
      - "traefik.http.routers.hangar-auth.tls.certresolver=default"
      - "traefik.http.routers.hangar-auth.tls.domains[0].main=benndorf.dev"
      - "traefik.http.routers.hangar-auth.tls.domains[0].sans=*.benndorf.dev"
    networks:
      - web
  kratos-migrate:
    image: "ghcr.io/papermc/hangarauth_kratos-migrate"
    build:
      context: kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    environment:
      DSN: "postgres://${POSTGRES_USER}:${POSTGRES_PW}@hangar_new_db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4"
      SECRETS_COOKIE: "supersecuresupersecure"
    labels:
      - "traefik.enable=true"
    networks:
      - web
  kratos:
    depends_on:
      - kratos-migrate
    image: "ghcr.io/papermc/hangarauth_kratos"
    build:
      context: kratos
    restart: unless-stopped
    environment:
      DSN: "postgres://${POSTGRES_USER}:${POSTGRES_PW}@hangar_new_db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4"
      SECRETS_COOKIE: "supersecuresupersecure"
      LOG_LEAK_SENSITIVE_VALUES: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.hangar-kauth.loadbalancer.server.port=4433"
      - "traefik.http.routers.hangar-kauth.rule=Host(`hangar-auth.benndorf.dev`) && PathPrefix(`/kratos`)"
      - "traefik.http.routers.hangar-kauth.entrypoints=web-secure"
      - "traefik.http.routers.hangar-kauth.tls=true"
      - "traefik.http.routers.hangar-kauth.tls.options=default"
      - "traefik.http.routers.hangar-kauth.tls.certresolver=default"
      - "traefik.http.routers.hangar-kauth.tls.domains[0].main=benndorf.dev"
      - "traefik.http.routers.hangar-kauth.tls.domains[0].sans=*.benndorf.dev"
    networks:
      - web
  hydra-migrate:
    image: "ghcr.io/papermc/hangarauth_hydra-migrate"
    build:
      context: hydra
    command: -c /etc/config/hydra/kratos.yml migrate sql -e --yes
    restart: on-failure
    environment:
      DSN: "postgres://${POSTGRES_USER}:${POSTGRES_PW}@hangar_new_db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4"
      SECRETS_SYSTEM: "supersecuresupersecure"
      OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT: "supersecuresupersecure"
    labels:
      - "traefik.enable=true"
    networks:
      - web
  hydra:
    depends_on:
      - hydra-migrate
    image: "ghcr.io/papermc/hangarauth_hydra"
    build:
      context: hydra
    restart: unless-stopped
    environment:
      DSN: "postgres://${POSTGRES_USER}:${POSTGRES_PW}@hangar_new_db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4"
      SECRETS_SYSTEM: "supersecuresupersecure"
      OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT: "supersecuresupersecure"
      LOG_LEAK_SENSITIVE_VALUES: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.hangar-oauth.loadbalancer.server.port=4444"
      - "traefik.http.routers.hangar-oauth.rule=Host(`hangar-oauth.benndorf.dev`)"
      - "traefik.http.routers.hangar-oauth.entrypoints=web-secure"
      - "traefik.http.routers.hangar-oauth.tls=true"
      - "traefik.http.routers.hangar-oauth.tls.options=default"
      - "traefik.http.routers.hangar-oauth.tls.certresolver=default"
      - "traefik.http.routers.hangar-oauth.tls.domains[0].main=benndorf.dev"
      - "traefik.http.routers.hangar-oauth.tls.domains[0].sans=*.benndorf.dev"
    networks:
      - web
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.hangar-auth-mail.loadbalancer.server.port=4436"
      - "traefik.http.routers.hangar-auth-mail.middlewares=basicauth@file"
      - "traefik.http.routers.hangar-auth-mail.rule=Host(`hangar-auth-mail.benndorf.dev`)"
      - "traefik.http.routers.hangar-auth-mail.entrypoints=web-secure"
      - "traefik.http.routers.hangar-auth-mail.tls=true"
      - "traefik.http.routers.hangar-auth-mail.tls.options=default"
      - "traefik.http.routers.hangar-auth-mail.tls.certresolver=default"
      - "traefik.http.routers.hangar-auth-mail.tls.domains[0].main=benndorf.dev"
      - "traefik.http.routers.hangar-auth-mail.tls.domains[0].sans=*.benndorf.dev"
    networks:
      - web

networks:
  web:
    name: traefik-overlay
    external: true
