name: Deploy

on:
  # allow manual dispatch
  workflow_dispatch:
  # run on PRs
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache Maven Deps
        uses: actions/cache@v2
        with:
          path: $GITHUB_WORKSPACE/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build backend
        run: mvn --batch-mode --errors --fail-at-end --show-version --no-transfer-progress -Dmaven.repo.local=$GITHUB_WORKSPACE/.m2/repository install

      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: "~/.cache/yarn"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install frontend deps
        env:
          CI: true
        run: (cd frontend && yarn install --frozen-lockfile --cache-folder ~/.cache/yarn)

      - name: Lint frontend
        env:
          CI: true
        run: (cd frontend && yarn lint)

      - name: Build frontend
        env:
          CI: true
        run: (cd frontend && yarn generate)

      - name: Docker
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          cd docker
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ secrets.CR_USER }} --password-stdin
          docker pull ghcr.io/papermc/paperauth:latest
          docker build . --tag ghcr.io/papermc/paperauth:$GITHUB_SHA --cache-from ghcr.io/papermc/paperauth:latest
          docker push ghcr.io/papermc/paperauth:$GITHUB_SHA
